apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-selafeou
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-selafeou:1f7ec7752d77d6548a065a462b84824f48e2b805@sha256:8687a170125949f02824f366b2c139d2be2bfdebd3da50df3c20e542dbd93d38
        name: container-image  
